version: '3'

services:
  tracker-database:
    image: mongo:latest
    ports:
      - 27017:27017
  tracker-api:
    env_file: .env
    build: .
    image: tracker-api:latest
    ports:
      - 80:5000
    depends_on: 
      - tracker-database
    environment:
      - DB_URI=mongodb://tracker-database/tracker
